version: '3.8'

services:
  db:
    container_name: hooly-db
    image: postgres:12
    volumes:
      - hooly-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:${PG_PORT}

  api:
    container_name: hooly-api
    # restart: always
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/api.dockerfile
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - ../config/.env
    environment:
      - PG_HOST=hooly-db
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  hooly-db:
